# pyright: basic, reportMissingImports=false, reportUnknownVariableType=false

"""Training loops and optimization."""

from pinn4csi.training.paper1 import (
    Paper1ExperimentConfig,
    Paper1ResultRow,
    Paper1SummaryRow,
    analyze_paper1_results,
    build_paper1_summary_rows,
    evaluate_paper1_model,
    render_paper1_summary_latex,
    run_paper1_experiments,
    save_paper1_analysis_json,
    save_paper1_results_csv,
    save_paper1_summary_json,
    save_paper1_summary_latex,
    set_experiment_seed,
    summarize_paper1_results,
)
from pinn4csi.training.paper2 import (
    Paper2BaselineExperimentConfig,
    Paper2BaselineResult,
    Paper2MatrixEntry,
    Paper2MultiEnvironmentExperimentConfig,
    Paper2MultiEnvironmentResultRow,
    Paper2PreparedDataConfig,
    build_paper2_leave_one_environment_out_matrix,
    evaluate_domain_adaptation_baseline,
    run_domain_adaptation_baselines,
    run_paper2_leave_one_environment_out_matrix,
    save_paper2_multi_environment_results_csv,
    train_domain_adaptation_epoch,
)
from pinn4csi.training.paper2_tta import (
    SYNTHETIC_SHIFT_LEVELS,
    TTAExperimentConfig,
    TTAReferenceStats,
    TTAResultRow,
    UnlabeledPreparedCSIDataset,
    adapt_model_for_tta,
    build_prepared_tta_loaders,
    build_synthetic_tta_loaders,
    compute_tta_reference_stats,
    evaluate_tta_classifier,
    run_tta_suite,
    save_tta_results_csv,
    train_source_only_tta_model,
)
from pinn4csi.training.pinn_trainer import PINNTrainer
from pinn4csi.training.trainer import BaseTrainer

__all__ = [
    "BaseTrainer",
    "PINNTrainer",
    "Paper1ExperimentConfig",
    "Paper1ResultRow",
    "Paper1SummaryRow",
    "run_paper1_experiments",
    "analyze_paper1_results",
    "build_paper1_summary_rows",
    "render_paper1_summary_latex",
    "save_paper1_analysis_json",
    "save_paper1_results_csv",
    "save_paper1_summary_json",
    "save_paper1_summary_latex",
    "summarize_paper1_results",
    "evaluate_paper1_model",
    "set_experiment_seed",
    "Paper2BaselineExperimentConfig",
    "Paper2BaselineResult",
    "Paper2PreparedDataConfig",
    "Paper2MultiEnvironmentExperimentConfig",
    "Paper2MatrixEntry",
    "Paper2MultiEnvironmentResultRow",
    "train_domain_adaptation_epoch",
    "evaluate_domain_adaptation_baseline",
    "run_domain_adaptation_baselines",
    "build_paper2_leave_one_environment_out_matrix",
    "run_paper2_leave_one_environment_out_matrix",
    "save_paper2_multi_environment_results_csv",
    "SYNTHETIC_SHIFT_LEVELS",
    "TTAExperimentConfig",
    "TTAReferenceStats",
    "TTAResultRow",
    "UnlabeledPreparedCSIDataset",
    "train_source_only_tta_model",
    "evaluate_tta_classifier",
    "compute_tta_reference_stats",
    "adapt_model_for_tta",
    "build_synthetic_tta_loaders",
    "build_prepared_tta_loaders",
    "run_tta_suite",
    "save_tta_results_csv",
]
